# cert-manager.io/v1 - Certificate management for Kubernetes (v1.11.0)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: myelixir-tls
  namespace: production
  labels:
    app: myelixir
    component: ingress
    environment: production
    managed-by: cert-manager
    security-tier: critical
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
    monitoring.myelixir.com/certificate-expiry-alert: "true"

spec:
  # Reference to the Kubernetes secret that will store the certificate
  secretName: myelixir-tls-secret
  
  # Certificate validity period (90 days)
  duration: "2160h"
  
  # Renewal window (15 days before expiry)
  renewBefore: "360h"
  
  # Certificate subject information
  subject:
    organizations:
      - MyElixir Healthcare
    organizationalUnits:
      - Security Operations
    countries:
      - US
    localities:
      - Production Environment
  
  # Private key configuration
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  
  # Certificate usage purposes
  usages:
    - server auth
    - client auth
  
  # Protected domain names
  dnsNames:
    - myelixir.com
    - api.myelixir.com
    - "*.myelixir.com"
  
  # Certificate issuer configuration
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io