apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  # SSL/TLS Configuration - Based on 7.2.1 Encryption Strategy
  ssl-protocols: "TLSv1.3"
  ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384"
  ssl-session-tickets: "off"
  ssl-session-timeout: "10m"
  use-http2: "true"

  # Request Size and Timeout Settings
  proxy-body-size: "50m"
  proxy-connect-timeout: "60"
  proxy-read-timeout: "60"
  proxy-send-timeout: "60"
  client-header-timeout: "60"
  client-body-timeout: "60"

  # Connection and Worker Settings - For 99.9% uptime target
  keep-alive: "75"
  keep-alive-requests: "100"
  worker-processes: "auto"
  worker-connections: "10240"
  large-client-header-buffers: "4 32k"

  # Security Settings - WAF and DDoS Protection
  enable-modsecurity: "true"
  enable-owasp-core-rules: "true"

  # Compression Settings - Performance Optimization
  enable-brotli: "true"
  brotli-level: "6"
  use-gzip: "true"
  gzip-level: "6"
  gzip-types: "application/json application/javascript text/css text/html text/plain"

  # Security Headers
  server-tokens: "off"
  hsts: "true"
  hsts-include-subdomains: "true"
  hsts-max-age: "31536000"

  # Additional Security Headers (applied via configuration snippet)
  configuration-snippet: |
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=()" always;

  # Error Handling
  custom-http-errors: "401,403,404,500,502,503,504"
  
  # Rate Limiting Settings - DDoS Protection
  limit-req-status-code: "429"
  limit-conn-status-code: "429"
  limit-rate-after: "100m"
  limit-rate: "10m"

  # Logging Configuration
  access-log-path: "/var/log/nginx/access.log"
  error-log-path: "/var/log/nginx/error.log"
  log-format-upstream: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id'