version: 2
updates:
  # Backend npm dependencies configuration
  - package-ecosystem: "npm"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    allow:
      - "patch"
      - "minor"
    assignees:
      - "@myelixir/backend-team"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    groups:
      medplum:
        patterns:
          - "@medplum/*"
        update-types:
          - "minor"
          - "patch"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "typescript"
        versions: ["5.x"]

  # Frontend npm dependencies configuration
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    allow:
      - "patch"
      - "minor"
    assignees:
      - "@myelixir/frontend-team"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    groups:
      mui:
        patterns:
          - "@mui/*"
        update-types:
          - "minor"
          - "patch"
      react-query:
        patterns:
          - "@tanstack/*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "typescript"
        versions: ["5.x"]

  # GitHub Actions dependencies configuration
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    assignees:
      - "@myelixir/devops-team"
    labels:
      - "dependencies"
      - "ci-cd"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"