apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: production
  labels:
    app: myelixir
    component: backend
    environment: production
    managed-by: manual
    rotation-schedule: quarterly
  annotations:
    secret-rotation-date: "2024-01-01"  # Initial rotation date
    secret-rotation-policy: "90-days"
    encryption-provider: "kubernetes.io/etcd"
    compliance-level: "hipaa-gdpr"
type: Opaque
data:
  # Azure AD B2C Authentication Configuration
  AZURE_AD_B2C_TENANT_NAME: ${BASE64_ENCODED_TENANT_NAME}
  AZURE_AD_B2C_CLIENT_ID: ${BASE64_ENCODED_CLIENT_ID}
  AZURE_AD_B2C_CLIENT_SECRET: ${BASE64_ENCODED_CLIENT_SECRET}
  AZURE_AD_B2C_SIGNUP_SIGNIN_POLICY: ${BASE64_ENCODED_SIGNUP_SIGNIN_POLICY}
  AZURE_AD_B2C_RESET_PASSWORD_POLICY: ${BASE64_ENCODED_RESET_PASSWORD_POLICY}
  AZURE_AD_B2C_EDIT_PROFILE_POLICY: ${BASE64_ENCODED_EDIT_PROFILE_POLICY}
  AZURE_AD_B2C_REDIRECT_URI: ${BASE64_ENCODED_REDIRECT_URI}

  # JWT Token Configuration
  JWT_ACCESS_TOKEN_SECRET: ${BASE64_ENCODED_ACCESS_TOKEN_SECRET}
  JWT_REFRESH_TOKEN_SECRET: ${BASE64_ENCODED_REFRESH_TOKEN_SECRET}

  # Medplum FHIR Server Configuration
  MEDPLUM_SERVER_URL: ${BASE64_ENCODED_MEDPLUM_URL}
  MEDPLUM_CLIENT_ID: ${BASE64_ENCODED_MEDPLUM_CLIENT_ID}
  MEDPLUM_CLIENT_SECRET: ${BASE64_ENCODED_MEDPLUM_CLIENT_SECRET}

  # Communication Service Configuration
  SMS_PROVIDER: ${BASE64_ENCODED_SMS_PROVIDER}
  SMS_API_KEY: ${BASE64_ENCODED_SMS_API_KEY}
  EMAIL_SERVICE: ${BASE64_ENCODED_EMAIL_SERVICE}
  EMAIL_API_KEY: ${BASE64_ENCODED_EMAIL_API_KEY}

  # Infrastructure Configuration
  ENCRYPTION_KEY: ${BASE64_ENCODED_ENCRYPTION_KEY}
  DATABASE_URL: ${BASE64_ENCODED_DATABASE_URL}
  REDIS_URL: ${BASE64_ENCODED_REDIS_URL}

  # Hyperledger Blockchain Configuration
  HYPERLEDGER_CERT: ${BASE64_ENCODED_HYPERLEDGER_CERT}
  HYPERLEDGER_PRIVATE_KEY: ${BASE64_ENCODED_HYPERLEDGER_PRIVATE_KEY}