apiVersion: v1
kind: ServiceAccount
metadata:
  name: myelixir-service-account
  namespace: default
  labels:
    app: myelixir
    component: rbac
    environment: production
    managed-by: kubernetes
    security-tier: platform
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    description: "Service account for MyElixir platform services"
    security.myelixir.com/audit-level: "high"
    security.myelixir.com/requires-rotation: "true"
    security.myelixir.com/rotation-period: "90d"
    compliance.myelixir.com/hipaa: "true"
    compliance.myelixir.com/gdpr: "true"