apiVersion: v1
kind: Secret
metadata:
  name: web-secrets
  namespace: myelixir
  labels:
    app: web
    component: frontend
    environment: production
    compliance: hipaa-gdpr
    secret-rotation: enabled
    backup-enabled: true
  annotations:
    secret.kubernetes.io/managed-by: myelixir-operator
    vault.hashicorp.com/agent-inject: "true"
    azure.keyvault/enabled: "true"
    secret.kubernetes.io/auto-rotation: enabled
    encryption.kubernetes.io/mode: aescbc
    encryption.kubernetes.io/key-id: myelixir-web-key
type: Opaque
stringData:
  # Azure AD B2C Authentication Configuration
  # Required for user authentication and authorization
  # Rotation period: 90 days
  VITE_AZURE_CLIENT_ID: "${AZURE_CLIENT_ID}"
  VITE_AZURE_AUTHORITY: "https://myelixir.b2clogin.com/myelixir.onmicrosoft.com/B2C_1_signin_signup"
  VITE_AZURE_KNOWN_AUTHORITIES: "myelixir.b2clogin.com"

  # Medplum FHIR Server Configuration
  # Required for FHIR data access and management
  # Rotation period: 90 days
  VITE_MEDPLUM_SERVER_URL: "https://api.medplum.com/fhir/R4"
  VITE_MEDPLUM_CLIENT_ID: "${MEDPLUM_CLIENT_ID}"

  # API Configuration
  # Required for backend service communication
  # Rotation period: 30 days
  VITE_API_KEY: "${API_KEY}"

  # Application Configuration
  # Environment-specific settings with enhanced security
  VITE_APP_VERSION: "1.0.0"
  VITE_ENVIRONMENT: "production"
  VITE_SECURE_COOKIE_ENABLED: "true"
  VITE_MFA_REQUIRED: "true"
  VITE_SESSION_TIMEOUT: "3600"
  VITE_API_TIMEOUT: "30000"

  # Security Configuration
  # HIPAA and GDPR compliance settings
  VITE_ENCRYPTION_ENABLED: "true"
  VITE_AUDIT_LOGGING_ENABLED: "true"
  VITE_STRICT_TRANSPORT_SECURITY: "true"
  VITE_XSS_PROTECTION_ENABLED: "true"
  VITE_CONTENT_SECURITY_POLICY: "default-src 'self'; connect-src 'self' https://api.medplum.com https://myelixir.b2clogin.com"